<?php

namespace ContainerLTlW6kd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Lmk9kmsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Lmk9kms' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Lmk9kms'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'request' => ['privates', '.errored..service_locator.Lmk9kms.Symfony\\Component\\BrowserKit\\Request', NULL, 'Cannot autowire service ".service_locator.Lmk9kms": it references class "Symfony\\Component\\BrowserKit\\Request" but no such service exists.'],
        ], [
            'request' => 'Symfony\\Component\\BrowserKit\\Request',
        ]);
    }
}
