<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLTlW6kd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLTlW6kd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLTlW6kd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLTlW6kd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLTlW6kd\App_KernelDevDebugContainer([
    'container.build_hash' => 'LTlW6kd',
    'container.build_id' => 'ff821a04',
    'container.build_time' => 1621782321,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLTlW6kd');
